source 'http://rubygems.org'
ruby '2.1.0'
gem 'sinatra'
gem 'thin'
gem 'mustache'
gem 'unicorn'
gem 'haml'
gem 'sass', '3.2.13'
gem 'coffee-script'
gem 'rack'
gem 'rack-session-mongo'
gem 'mongo'
gem 'rake'
gem 'yajl-ruby'
gem 'shotgun'

